version: '3.8'

services:
  postgres:
    image: postgres:16

    container_name: bookinghub_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: miss23
      POSTGRES_DB: banco_bkhub

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./wal_archive:/wal_archive

    command: >
      postgres
      -c wal_level=replica
      -c archive_mode=on
      -c archive_command='cp %p /wal_archive/%f'
      -c archive_timeout=60

volumes:
  postgres_data: